server:
  port: 8888

spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      # XE版的最后要XE 完整版的要orcl
      url: jdbc:oracle:thin:@localhost:1521:orcl
      username: system
      password: system

mybatis:
  mapper-locations: classpath:daoImpl/b/*/*Mapper.xml
  configuration:
    jdbc-type-for-null: VARCHAR