server:
  port: 9361

spring:
  datasource:
    url: jdbc:sqlserver://10.60.254.42:1420;databaseName=A_Database
    username: sa
    password: helloworld@914
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  identity: SQLSERVER