server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dataintegration
    username: root
    password: weikaixuan
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml