server:
  port: 9363

spring:
  datasource:
    url: jdbc:mysql:// 10.60.254.37:3420/C_Database
    username: root
    password: helloworld@914
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml